afternoon_edit: true
capital:
- Sri Lanka
- Asia
- Colombo
classic:
- Canada
- '1'
- Americas
- 36155487
- 9984670
- UTC-08:00
dns:
- Saint Vincent and the Grenadines
- Americas
- .vc
flag:
- Vanuatu
- Oceania
- VU
map:
- Tuvalu
- -8
- 178
- Oceania
morning_edit: false
