afternoon_edit: false
capital:
- American Samoa
- Oceania
- Pago Pago
classic:
- Guyana
- '592'
- Americas
- 746900
- 214969
- UTC-04:00
dns:
- Iceland
- Europe
- .is
flag:
- Lithuania
- Europe
- LT
map:
- Saudi Arabia
- 25
- 45
- Asia
morning_edit: false
