"classic": ['Mozambique', '258', 'Africa', 26423700, 801590, 'UTC+02:00']
"map": []
"flag": ["Myanmar", "Asia", "MM"]
"capital": ["Papua New Guinea", "Oceania", "Port Moresby"]
"dns": ["Slovenia", "Europe", ".si"]