afternoon_edit: true
capital:
- Antigua and Barbuda
- Americas
- Saint Johns
classic:
- San Marino
- '378'
- Europe
- 33005
- 61
- UTC+01:00
dns:
- Qatar
- Asia
- .qa
flag:
- Qatar
- Asia
- QA
map:
- Uganda
- 1
- 32
- Africa
morning_edit: false
