afternoon_edit: false
capital:
- Jersey
- Europe
- Saint Helier
classic:
- Cameroon
- '237'
- Africa
- 22709892
- 475442
- UTC+01:00
dns:
- Libya
- Africa
- .ly
flag:
- Denmark
- Europe
- DK
map:
- Russian Federation
- 60
- 100
- Europe
morning_edit: false
