afternoon_edit: false
capital:
- Nigeria
- Africa
- Abuja
classic:
- Honduras
- '504'
- Americas
- 8576532
- 112492
- UTC-06:00
dns:
- Togo
- Africa
- .tg
flag:
- Iceland
- Europe
- IS
map:
- Korea (Democratic People s Republic of)
- 40
- 127
- Asia
morning_edit: false
