afternoon_edit: true
capital:
- Switzerland
- Europe
- Bern
classic:
- Kyrgyzstan
- '996'
- Asia
- 6047800
- 199951
- UTC+06:00
dns:
- Spain
- Europe
- .es
flag:
- Swaziland
- Africa
- SZ
map:
- Algeria
- 28
- 3
- Africa
morning_edit: false
